# vim:fileencoding=utf-8:foldmethod=marker

# Theme
include current-theme.conf

# Fonts
font_family      DejaVuSansM Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        17.0

# Window
window_padding_width    0 10
confirm_os_window_close 0
macos_titlebar_color    #313244

# Cursor
cursor_shape block

# Keymaps
map cmd+enter no_op
map cmd+r     no_op
